### PR TITLE
Added presets for train and moo emotes from all races and genders

### PR DESCRIPTION
**Pull request by brunochampoux**
This is the annoying choo-choo effect that annoying players bind to various spells and macros.

### CODE REVIEW

**Comment by funkydude** [comment]
Nice work. I don't see what is specific to TBC about this?
A better name would be `Emote: Train (choo-choo)`
Should probably also add the remaining non-TBC races.

**Comment by funkydude** [comment]
Nothing will happen when muting invalid IDs.
I can test and verify your PR on retail.
You might be able to find some on https://wow.tools/files/sounds.php#search=&page=1

**Comment by brunochampoux** [comment]
Sorry for the delay.

I added all the other train emotes I could find for Retail, with a bonus new preset for moo emotes (that one is the same sound for all races). Renamed the preset as you suggested.

**Comment by funkydude** [comment]
Excellent work, thanks!

**Pull request merged**
