### PR TITLE
Add new preset: Zereth Mortis waterfall

### PR DESCRIPTION
**Pull request by Lunaeria**
Kind of a niche preset, but if in Zereth Mortis fishing for the jellyfish mount, the waterfall sounds are likely to drive you bananas, so maybe this could be useful to someone other than me.

Hopefully I've managed to do everything correctly, this is my first time properly using GitHub!

### CODE REVIEW

**Comment by funkydude** [comment]
That's a lot of sound files, are you sure they are all related to that specific waterfall?

**Comment by Lunaeria** [comment]
> That's a lot of sound files, are you sure they are all related to that specific waterfall?

I took them from a macro someone shared on wowhead; I do think a fair few of them aren't exclusive to the Zereth Mortis waterfall, but I had been using the macro as a temporary mute while fishing, and thought it'd be useful to have as a preset for this addon to more easily toggle it on and off. 

That being said, it's such a niche thing and I suppose it'd be a shame if someone toggled it on and accidentally forgot to untoggle it. I suppose I can stick with the macro, in the end. Feel free to close/disregard this suggestion! Entirely up to you.

**Comment by funkydude** [comment]
I don't mind merging it, it was more a question of if you are willing to go through them yourself and do a "spring clean"

**Comment by Lunaeria** [comment]
Hello, sorry! I tried to sort through the sound files in-game but couldn't quite figure them out. Since the preset is so incredibly niche, and the mute exists as a macro anyway, I suppose it's a silly suggestion anyway. I'll close this pull request for now. Sorry!

**Pull request closed without merging**
