### PR TITLE
Add Mount: Sunwarmed Furline Preset

### PR DESCRIPTION
**Pull request by cr4ckp0t**
The new store mount, Sunwarmed Furline, is great but the sounds are super annoying. So I added a preset and figured I'd share it with others.

### CODE REVIEW

**Comment by cr4ckp0t** [comment]
For what it's worth, I'm sure the sounds involved could be pruned down to the actual ones. I just added any sound package from "catmount".

**Comment by funkydude** [comment]
Thanks for your work. I'd appreciate it if you could take the time to "prune it to the actual ones" if possible?

**Comment by funkydude** [comment]
@cr4ckp0t Do you plan on doing this?

**Comment by cr4ckp0t** [comment]
Yeah for sure, I can work on that tomorrow. Just been busy with 9.2 and my other addon projects, so I haven't been able to dig in.

**Comment by cr4ckp0t** [comment]
Okay I pared it down as best I could. My kitteh has been silent thus far.

**Comment by funkydude** [comment]
Awesome. Could you also add the names of the sound files (commented out) in the same way the other sounds are? It makes it easier to read/reference them if anyone is reading the file.

**Comment by cr4ckp0t** [comment]
Yeah, turns out I may have missed a sound or two so I'm gonna have to investigate anyways.

**Comment by cr4ckp0t** [comment]
Okay, it should be good now.

**Comment by funkydude** [comment]
Thanks!

**Pull request merged**
