### PR TITLE
Add new preset: Dornogal Inn (Humming/Fidgeting)

### PR DESCRIPTION
**Pull request by biggianteye**
<s>This is the innkeeper in Dornogal. He is constantly making noises.</s>

Mute the sounds heard in the inn in Dornogal. These are predominantly from innkeeper Ronesh, but also includes other Earthen fidgeting sounds that can be heard in the inn.

### CODE REVIEW

**Comment by funkydude** [comment]
Hey. I appreciate the pull request but when creating presets you need to be sure you are only adding the correct sounds.
You can do this easily in game by simply using the preview button in the addon:
image

Doing this you can see that at least the first 2 sounds sound like fighting sounds and are not related to him humming, so they should be removed from the list.

The last 2 sounds might also be questionable as they may be the sounds he makes when interacting with him, but maybe you intentionally want that?

**Comment by funkydude** [comment]
Do you plan on addressing this?

**Comment by biggianteye** [comment]
Sorry for the delayed response.

> Doing this you can see that at least the first 2 sounds sound like fighting sounds and are not related to him humming, so they should be removed from the list.

These do indeed sound like generic fighting sounds, but they are categorised as `earthendwarfmale_fidget13`, just like the humming is. They are audible in the inn, but not directly from Ronesh so I have removed them.

> The last 2 sounds might also be questionable as they may be the sounds he makes when interacting with him, but maybe you intentionally want that?

These two are also audible in the inn but happenly infrequently, so I couldn't definitively attribute them to Ronesh, so I have removed them as well.

However these changes now make me wonder if this is a useful preset to have at all in its current state, given there are only three sounds left. If it were merged, I would still be manually muting the other four sounds. Alternatively, I could rename the preset to be about the _inn_ rather than the NPC. What do you think?

Options, in no particular order:
* Switch the preset to the inn.
* It's useful as is. Merge it.
* It's not useful. Scrap the PR.

I'm fine with any of those. Whichever fits in to what you want for the addon.

**Comment by biggianteye** [comment]
> Changing it to "Zone: Dornogal Inn (Humming/Fidgeting)" sounds good! Thanks for testing and verifying the sounds.

I've updated the PR to be about the inn rather than the NPC and reinstated the additional sounds you can hear in the inn.

**Comment by funkydude** [comment]
Nice work, thanks!

**Comment by funkydude** [comment]
I think there is also a female version of this, just outside of the inn, if you're interested in adding that also.

**Comment by BloodMoonTalon** [comment]
Hey All, first of all ty for this addon
Ive just signed up to github just to request something
There are "Oathsworn Peacekeeper" right beside single target PVP Training Dummy in Dornogall
Ive tried every sound id inside wowhead to mute them but to no avail
If u could make a preset for them i would be so happy

**Comment by biggianteye** [comment]
> I think there is also a female version of this, just outside of the inn, if you're interested in adding that also.

It's not something that's affected me directly, so I'll leave it as an itch for someone else to scratch.

**Comment by biggianteye** [comment]
> Nice work, thanks!

No worries. Thanks for merging it!

**Pull request merged**
