### PR TITLE
Collection/Custom Preset Functionality

### PR DESCRIPTION
**Pull request by Schtenk**
Collection/custom preset functionality for making managing muting larger amounts of sound IDs easier(Adds a new Tab)

### CODE REVIEW

**Comment by Schtenk** [comment]
image

Preview of it in-game

**Comment by funkydude** [comment]
Nice work, but I worry this might lead to more confusion in the UI options, I already get a lot of people struggling.

I think I would rather these be added as presets so the majority of users can just select them, and grow the presets list to as long as needed. Maybe even have dropdowns based on categories of sounds in the presets.

Are you interested in contributing that?

**Comment by Schtenk** [comment]
I understand your concern, maybe this or something similar can replace/improve/extend the Sounds tab would be a nice compromise since this in essence provide a similar function (I.e muting specific sounds of the users choosing). 

One of the reasons I made this was managing muting multiple sounds and naming each one started becomming a chore.  I liked the idea of muting mutiple sounds under a single name which presets in a way does provide but without the freedom of choosing specifcally which sounds you want or don't want to mute.

Am I wrong by thinking most of the confusion regarding muting sounds is a product of the "difficulty" or non ease of finding the sound IDs of the specific sounds users would want to mute?

**Comment by Schtenk** [comment]
image
Maybe something like this is a nice compromise?

**Comment by Schtenk** [comment]
Any thoughts?

**Comment by funkydude** [comment]
>Am I wrong by thinking most of the confusion regarding muting sounds is a product of the "difficulty" or non ease of finding the sound IDs of the specific sounds users would want to mute?

Yup. With that already high-ish barrier I don't also want to risk intimidating users by having an overly large amount of options for an addon that, well, only has 1 purpose.

In regards to your latest changes, I think I'd be happier if you could simplify the amount of churn/change you're making in the options code. If you're going for the "multiple sounds with 1 nickname" approach, I think you can preserve most of the original code, do a check for say a comma in the input box, and do the more advanced checking in that separate if statement. This should make it easier for me to check the new code.

**Comment by Schtenk** [comment]
If I understand correctly you want the UI to stay/mostly stay the same but with being able input comma seperated sound ids? If thats the case I think you loose too much of the overview of the sound ids you are muting and complicates things a bunch with the preview sound functionality.

**Pull request closed without merging**
